apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nestjs-job-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: nestjs-sa
    namespace: default
roleRef:
  kind: Role
  name: nestjs-job-role
  apiGroup: rbac.authorization.k8s.io
